## Global values for parent chart and subcharts.
global:
  spring:
    ## Use default consul address `consul-agent.local` or use pod host IP.
    useDefaultConsul: true

security:
  frontend:
    resources:
      limits:
        memory: 1000M
    enabled: true
  backend:
    resources:
      limits:
        memory: 1000M
    enabled: true


infrastructure:
  genericServices:
    security-db:
      storageClassName: 'nfs-retain'
      volumes:
        - name: security-db-data
          persistentVolumeClaim:
            claimName: security-db-data
      volumeMounts:
        - name: security-db-data
          mountPath: /pg/14/data
      enabled: true