## Global values for parent chart and subcharts.
global:
  ## Current build tag for images of this project.
  imageTag: "${docker.image.tag}"
  ## Global values for all spring services.
  spring:
    ## Global environment variables injected in every spring service.
    env:
      SPRING_CLOUD_CONSUL_CONFIG_PREFIX: "security-admin-master"
      SPRING_CLOUD_CONSUL_CONFIG_FORMAT: YAML
      JAVA_OPTS: "-XX:MaxRAMPercentage=75"

# list of spring boot services using the database with specific values for each
security:
  frontend:
    replicaCount: 1
    enabled: true
    imageName: security-admin/frontend
    actuatorPath: "actuator"
    env:
      JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
      JAVA_OPTS: -Xmx300m
      ACCESS_SERVICE_USERINFO_URL: "http://backend:8080/userinfo"
      ACCESS_SERVICE_URL: "http://backend:8080"
      ACCESS_EMAIL_AS_USERNAME: "true"
    ingress:
      path: /

  backend:
    replicaCount: 1
    enabled: true
    imageName: security-admin/backend
    actuatorPath: "actuator"
    overrideDbName: "security"
    env:
      JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
      JAVA_OPTS: -Xmx400m
      SERVER_PORT: 8080
      SERVER_USE_FORWARD_HEADERS: true
      ACCESS_KEYCLOAK_SERVER_URL: "https://keycloak-dev.i-novus.ru/auth"
      ACCESS_KEYCLOAK_REALM: security-admin
      ACCESS_ORGANIZATION_PERSIST_MODE: rest
      ACCESS_EMAIL_AS_USERNAME: true
      AUDIT_CLIENT_ENABLED: false
    contextPath: service
    ingress:
      path: /service


infrastructure:
  genericServices:
    security-db:
      enabled: true

