# global values for parent chart and subcharts
global:
  observability:
    ## Enable observability data collection.
    enabled: false
  spring:
    dbUrl: "jdbc:postgresql://security-db:5432/"
    dbUsername: "postgres"
    dbPassword: "postgres"
    useDefaultConsul: false

# list of spring boot services using the database with specific values for each
security:
  backend:
    resources:
      limits:
        memory: 1000M
    enabled: true
  frontend:
    resources:
      limits:
        memory: 1000M
    enabled: true

infrastructure:
  genericServices:
    security-db:
      enabled: true
      storageClassName: 'nfs-retain'
      resources:
        limits:
          memory: 1024M
      replicaCount: 1
      volumes:
        - name: security-db-data
          persistentVolumeClaim:
            claimName: security-db-data
      volumeMounts:
        - mountPath: /pg/14/data
          name: security-db-data
      env:
        POSTGRES_PASSWORD: postgres
      initContainers:
        - name: permission-init
          image: alpine
          command: [ "sh","-c","chown -R 70:70 /pg/14/data" ]
          volumeMounts:
            - name: security-db-data
              mountPath: /pg/14/data
