version: "3.7"

services:
  frontend:
    image: "${DOCKER_REGISTRY}/security-admin/frontend:${TAG}"

  auth-gateway:
    image: "${DOCKER_REGISTRY}/security-admin/auth-gateway:${TAG}"

  security-admin-backend:
    image: "${DOCKER_REGISTRY}/security-admin/backend:${TAG}"