version: "3.6"
services:
  backend:
    build:
      context: security-admin-backend
      args:
        JAR_FILE: target/backend.jar
    image: "538721144237.dkr.ecr.eu-west-1.amazonaws.com/lkb/security-admin-backend:${TAG}"
  frontend:
    build:
      context: security-admin-frontend
      args:
        JAR_FILE: target/frontend.jar
    image: "538721144237.dkr.ecr.eu-west-1.amazonaws.com/lkb/security-admin-frontend:${TAG}"
