version: "3.7"

services:

  db:
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/pg/14/data
    ports:
      - 5432
    deploy:
      restart_policy:
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512m
      placement:
        constraints:
          - node.labels.type == db

  redis:
    environment:
      - REDIS_PASSWORD=0b4d68e7-a887-4a45-b40f-c477aa382e33
    deploy:
      restart_policy:
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512m
      placement:
        constraints:
          - node.labels.type == db

  backend:
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/security
    depends_on:
      - db

volumes:
  db-data:
