version: "3.6"

services:

  frontend:
    environment:
      - JAVA_OPTS=-Xmx300m
      - SECURITY_OAUTH2_AUTH_SERVER_URI=http://docker.one:8278
      - SECURITY_OAUTH2_CLIENT_CLIENT_ID=frontend
      - SECURITY_OAUTH2_CLIENT_CLIENT_SECRET=ca12a678-b275-499b-a778-750bad4d0a77
      - JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
    ports:
      - 8080
    deploy:
      resources:
        limits:
          memory: 1024M
      restart_policy:
        max_attempts: 3
      placement:
        constraints:
          [node.hostname == os-4]

  auth-gateway:
    environment:
      - JAVA_OPTS=-Xmx400m
      - SERVER_PORT=8080
      - SERVER_USE_FORWARD_HEADERS=true
      - ACCESS_KEYCLOAK_SERVER_URL=https://keycloak8.i-novus.ru/auth
      - ACCESS_KEYCLOAK_REALM=security-admin
      - ACCESS_KEYCLOAK_CLIENT_CLIENT_ID=auth-gateway
      - ACCESS_KEYCLOAK_CLIENT_CLIENT_SECRET=0a889967-3fa4-4dd7-898c-7625e99bd793
      - ACCESS_KEYCLOAK_ADMIN_CLIENT_ID=auth-gateway
      - ACCESS_KEYCLOAK_ADMIN_CLIENT_SECRET=0a889967-3fa4-4dd7-898c-7625e99bd793
      - ACCESS_ORGANIZATION_PERSIST_MODE=rest
      - JAXRS_SWAGGER_AUTH_TOKEN_URI=http://docker.one:8278/oauth/token
    ports:
      - 8080
    deploy:
      resources:
        limits:
          memory: 1024M
      placement:
        constraints:
          [node.hostname == os-4]
