version: "3.6"

services:

  db:
    volumes:
      - db-data:/pg/11/data
    ports:
      - 5432
    deploy:
      resources:
        limits:
          memory: 1024M
      placement:
        constraints:
          [node.hostname == os-4]

  auth-gateway:
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/security
    depends_on:
      - db

volumes:
  db-data:
