version: "3.7"

services:

  frontend:
    environment:
      - JAVA_OPTS=-Xmx300m
      - SECURITY_OAUTH2_AUTH_SERVER_URI=http://yandex.develop:8278
      - SECURITY_OAUTH2_CLIENT_CLIENT_ID=frontend
      - SECURITY_OAUTH2_CLIENT_CLIENT_SECRET=ca12a678-b275-499b-a778-750bad4d0a77
      - SECURITY_OAUTH2_CLIENT_ACCESS_TOKEN_URI=http://auth-gateway:8080/oauth/token
      - SECURITY_OAUTH2_RESOURCE_USER_INFO_URI=http://auth-gateway:8080/userinfo
      - ACCESS_SERVICE_URL=http://auth-gateway:8080/api
      - JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
      - SPRING_CLOUD_CONSUL_CONFIG_PREFIX=security-admin-master
      - ACCESS_EMAIL_AS_USERNAME=true
    ports:
      - 8080
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024m
      restart_policy:
        max_attempts: 3
      placement:
        constraints:
          - node.labels.type == service

  auth-gateway:
    environment:
      - JAVA_OPTS=-Xmx400m
      - SERVER_PORT=8080
      - SERVER_USE_FORWARD_HEADERS=true
      - ACCESS_KEYCLOAK_SERVER_URL=https://keycloak8.i-novus.ru/auth
      - ACCESS_KEYCLOAK_REALM=security-admin
      - ACCESS_KEYCLOAK_CLIENT_CLIENT_ID=auth-gateway
      - ACCESS_KEYCLOAK_CLIENT_CLIENT_SECRET=0a889967-3fa4-4dd7-898c-7625e99bd793
      - ACCESS_KEYCLOAK_ADMIN_CLIENT_ID=auth-gateway
      - ACCESS_KEYCLOAK_ADMIN_CLIENT_SECRET=0a889967-3fa4-4dd7-898c-7625e99bd793
      - ACCESS_ORGANIZATION_PERSIST_MODE=rest
      - JAXRS_SWAGGER_AUTH_TOKEN_URI=http://yandex.develop:8278/oauth/token
      - ACCESS_EMAIL_AS_USERNAME=true
      - AUDIT_CLIENT_ENABLED=false
      - SPRING_CLOUD_CONSUL_CONFIG_PREFIX=security-admin-master
      - SPRING_CLOUD_CONSUL_CONFIG_FORMAT=YAML
      - SPRING_REDIS_DATABASE=0
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_PASSWORD=0b4d68e7-a887-4a45-b40f-c477aa382e33
      - SPRING_REDIS_TIMEOUT=60000
      - SPRING_SESSION_STORE_TYPE=redis
      - ACCESS_JWT_SIGNING_KEY=-----BEGIN PRIVATE KEY-----MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDhCthiz9BiC2jih+Qs699QllgoDdHhE0XQ1b4MzA1/qFcSUkzDN9RBtdI0RISjST/xWHSPubuaoPY2dR4YdoggcwzdIASeuadExKN+DZkviWnLfRc6GnBrv6z9rxNXSAZMSey6o8MpzrBBr2SCdSdVVBVXHT9RWqdHdLmkW7SU6QJ1qaZxGCYSPM0mejGhqiYi/Hew8pKliqyUdpRp/qOwFDZLNy7KwC3rDEz42zBlbn+r7e634rYXJNz9KE1GUfbp3rfCKAUrpps4o0e7ycRM+u5YtTQ4gwYGn9Be2hgeuFGUgHjVMIZYT1i1NzZTI6fClyRQprtwulX6Tm1D06aVAgMBAAECggEAX101LUpbR/EF1Vk4vECINaJAYVjZ48NDBqhNDSc7YSl5HG570Q5LiD0Agt22R2u3CRMu8ekHMxOawqEGy98O+JFIljwHOSv7UgzyK2yfyaE1j+HGgfzKPx7OtAII9Ce1Y4bAJqdXANRxpKQqt43lyScElBH0zwjXclRohtnFwIPh1B27LzvC17+r3QSMwIMJ6fl9y8BqQ5EGWG6R4SJaFoFdo1+MrWe/kb/aovoUJ3LuXUZLKttV7oSNV8SMltcXHSAL3kNMBx89zjdwMOiSgubnQXFed2hA4OWN24afILVAhMwQP3LQW1KNwRKuSuEL7WpDccIOeaaZ3IcEAyqxgQKBgQD4xz5jC93issQhArSFh+BpzJIiKTm1z7c37ol54aqQJgy6exWgba9aEYOSqcfxGYBGqiEGo0JIfDKkZWqGQ5xfwNQoTsP7r0qMV046kjiGkyIyu3SwMmR+lHqecC1BcNugbPDSgjsoHKPtlF4Qhrb6krKXnsN8+U+8Ye624s/g2QKBgQDnkzY2HNu0f+6g4zTAE0zwidtZDvJwBvIUEVyef7w1huZx/5Lvn0iIGf23z/jReot2sQIumwA2pj4tkK5ve51PlyXWE1kHNtz9Y7xhaTNodw8ZQ96MbGm+odW2EgfZrAPWolai77VlxadHZzIDpBfPFhlqZ24QTktpOkTwSMPeHQKBgQCtLlY5sOsXgwaRTEbKpdoNDIG2EijAbgbHguBk3jlT+4jk0AYwFer5sjN7h4FOT0hC6O/wpPnhZ8QBOTA8oxhad+u424wGyvIEXEpy75M163rlAiWq+omGrGnnnYODiML7HJtQj6QKulVLb/tDWeRK7pAwiC7h8tQU+b+pxJ6dkQKBgAIHOgxTSGFWVYK3OrkL8jqRGoi3JsxwYyJl3IfO2pkla1NIR8Mtg/cdMymu+qDrD9mkRz6dQO05m4XOpJh5XrFZw40Sck8r3deiTf4Ua8zYbhtsisB0GqD+zd5gXg08AnSYy2V18ALKLmLjtn5tq3+209YovcAKz4JGbmAkYwLJAoGAdFyiUh5kGRUOUtzeEHwk3ISCcRm839mpn023yKs7Fzg+3I4uVtXvc5amXkO26VFHi7+BDiKkQWaH7ng/6DH9Cy3Cudqlyos9dkgFv0leqB949WhQXrFsBJyS9ZFKxh6jQ1RDsrGKhBWvvpNBDzF4Mfk43JQ9PzMjPiTiAUd+SKQ=-----END PRIVATE KEY-----
      - ACCESS_JWT_VERIFIER_KEY=-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4QrYYs/QYgto4ofkLOvfUJZYKA3R4RNF0NW+DMwNf6hXElJMwzfUQbXSNESEo0k/8Vh0j7m7mqD2NnUeGHaIIHMM3SAEnrmnRMSjfg2ZL4lpy30XOhpwa7+s/a8TV0gGTEnsuqPDKc6wQa9kgnUnVVQVVx0/UVqnR3S5pFu0lOkCdammcRgmEjzNJnoxoaomIvx3sPKSpYqslHaUaf6jsBQ2SzcuysAt6wxM+NswZW5/q+3ut+K2FyTc/ShNRlH26d63wigFK6abOKNHu8nETPruWLU0OIMGBp/QXtoYHrhRlIB41TCGWE9YtTc2UyOnwpckUKa7cLpV+k5tQ9OmlQIDAQAB-----END PUBLIC KEY-----
    ports:
      - 8080
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 1024m
      placement:
        constraints:
          - node.labels.type == service
