version: "3.6"

services:

  frontend:
    environment:
      - JAVA_OPTS=-Xmx300m
      - SECURITY_OAUTH2_AUTH_SERVER_URI=http://yandex.develop:8278
      - SECURITY_OAUTH2_CLIENT_CLIENT_ID=frontend
      - SECURITY_OAUTH2_CLIENT_CLIENT_SECRET=ca12a678-b275-499b-a778-750bad4d0a77
      - SECURITY_OAUTH2_CLIENT_ACCESS_TOKEN_URI=http://auth-gateway:8080/oauth/token
      - SECURITY_OAUTH2_RESOURCE_USER_INFO_URI=http://auth-gateway:8080/userinfo
      - ACCESS_SERVICE_URL=http://auth-gateway:8080/api
      - JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
    ports:
      - 8080
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: 1024m
      restart_policy:
        max_attempts: 3
      placement:
        constraints:
          - node.labels.type == service

  auth-gateway:
    environment:
      - JAVA_OPTS=-Xmx400m
      - SERVER_PORT=8080
      - SERVER_USE_FORWARD_HEADERS=true
      - ACCESS_KEYCLOAK_SERVER_URL=https://keycloak8.i-novus.ru/auth
      - ACCESS_KEYCLOAK_REALM=security-admin
      - ACCESS_KEYCLOAK_CLIENT_CLIENT_ID=auth-gateway
      - ACCESS_KEYCLOAK_CLIENT_CLIENT_SECRET=0a889967-3fa4-4dd7-898c-7625e99bd793
      - ACCESS_KEYCLOAK_ADMIN_CLIENT_ID=auth-gateway
      - ACCESS_KEYCLOAK_ADMIN_CLIENT_SECRET=0a889967-3fa4-4dd7-898c-7625e99bd793
      - ACCESS_ORGANIZATION_PERSIST_MODE=rest
      - JAXRS_SWAGGER_AUTH_TOKEN_URI=http://yandex.develop:8278/oauth/token
      - ACCESS_EMAIL_AS_USERNAME=true
    ports:
      - 8080
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: 1024m
      placement:
        constraints:
          - node.labels.type == service
