version: "3.6"
services:
  backend:
    build:
      context: security-admin-backend
      args:
        JAR_FILE: target/backend.jar
  frontend:
    build:
      context: security-admin-frontend
      args:
        JAR_FILE: target/frontend.jar
