version: "3.7"

services:

  frontend:
    environment:
      - JAVA_OPTS=-Xmx300m
      - ACCESS_SERVICE_USERINFO_URL=http://backend:8080/userinfo
      - ACCESS_SERVICE_URL=http://backend:8080/api
      - JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
      - SPRING_CLOUD_CONSUL_CONFIG_PREFIX=security-admin-master
      - ACCESS_EMAIL_AS_USERNAME=true
    ports:
      - 8080
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024m
      restart_policy:
        max_attempts: 3
      placement:
        constraints:
          - node.labels.type == service

  backend:
    environment:
      - JAVA_OPTS=-Xmx400m
      - SERVER_PORT=8080
      - SERVER_USE_FORWARD_HEADERS=true
      - ACCESS_KEYCLOAK_SERVER_URL=https://keycloak8.i-novus.ru/auth
      - ACCESS_KEYCLOAK_REALM=security-admin
      - ACCESS_ORGANIZATION_PERSIST_MODE=rest
      - ACCESS_EMAIL_AS_USERNAME=true
      - AUDIT_CLIENT_ENABLED=false
      - SPRING_CLOUD_CONSUL_CONFIG_PREFIX=security-admin-master
      - SPRING_CLOUD_CONSUL_CONFIG_FORMAT=YAML
      - SPRING_REDIS_DATABASE=0
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_PASSWORD=0b4d68e7-a887-4a45-b40f-c477aa382e33
      - SPRING_REDIS_TIMEOUT=60000
      - SPRING_SESSION_STORE_TYPE=redis
    ports:
      - 8080
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 1024m
      restart_policy:
        max_attempts: 3
      placement:
        constraints:
          - node.labels.type == service
