version: "3.7"

services:

  frontend:
    build:
      context: security-admin-frontend
      args:
        JAR_FILE: target/access-web.jar

  backend:
    build:
      context: security-admin-backend
      args:
        JAR_FILE: target/access-service.jar
