version: "3.8"

services:

  frontend:
    build:
      context: security-admin-frontend
      args:
        JAR_FILE: target/access-web.jar

  auth-gateway:
    build:
      context: auth-gateway
      args:
        JAR_FILE: target/auth-gateway.jar