version: "3.6"
services:
  keycloak-db:
    ports:
    - "5432"
  keycloak:
    ports:
    - "8080"
    - "8443"
  db:
    ports:
    - "5432"
  backend:
    ports:
    - "8080"
  frontend:
    ports:
    - "8080"