version: "3.6"
services:
  backend:
    build:
      context: security-admin-backend
      args:
        JAR_FILE: target/access-service.jar
    image: "538721144237.dkr.ecr.eu-west-1.amazonaws.com/security-admin/access-service:${TAG}"

  auth-gateway:
    build:
      context: auth-gateway
      args:
        JAR_FILE: target/auth-gateway.jar
    image: "538721144237.dkr.ecr.eu-west-1.amazonaws.com/security-admin/auth-gateway:${TAG}"

  frontend:
    build:
      context: security-admin-frontend
      args:
        JAR_FILE: target/access-web.jar
    image: "538721144237.dkr.ecr.eu-west-1.amazonaws.com/security-admin/access-web:${TAG}"
