version: "3.7"

services:

  frontend:
    build:
      context: security-admin-frontend
      args:
        JAR_FILE: target/access-web.jar

  auth-gateway:
    build:
      context: auth-gateway
      args:
        JAR_FILE: target/auth-gateway.jar

  security-admin-backend:
    build:
      context: security-admin-backend
      args:
        JAR_FILE: target/security-admin-backend.jar