version: "3.7"

services:

  db:
    volumes:
      - db-data:/pg/11/data
    ports:
      - 5432
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: 512m
      placement:
        constraints:
          - node.labels.type == db

  services:
    redis:
      environment:
        - REDIS_PASSWORD=borisBritva

  auth-gateway:
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/security
    depends_on:
      - db

volumes:
  db-data:
