# list of all generic services with specific values for each
genericServices:
  security-db:
    port: 5432
    imageName: /security-admin/db
    imageTag: ${docker.image.tag}
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: 1024M
    replicaCount: 1
    volumes:
      - name: demo-db-data
        persistentVolumeClaim:
          claimName: demo-db-data
    volumeMounts:
      - mountPath: /pg/12/data
        name: demo-db-data
    env:
      POSTGRES_PASSWORD: postgres
    initContainers:
      - name: permission-init
        image: alpine
        command: [ "sh","-c","chown -R 70:70 /pg/14/data" ]
        volumeMounts:
          - name: security-db-data
            mountPath: /pg/14/data
