@startuml

title Auth-gateway authentication flow


actor "User (browser)"

"User (browser)" -> "frontend": localhost:8080
"frontend" --> "frontend": /login
"frontend" --> "auth-gateway": /oauth/authorize

"auth-gateway" --> "auth-gateway": /login/keycloak
"auth-gateway" --> "keycloak": /.../openid-connect/auth

"keycloak" ->> "User (browser)": Форма логина
"User (browser)" -> "keycloak": Пользователь \nвводит \nлогин / пароль

"keycloak" --> "auth-gateway": /login/keycloak?code=...
"auth-gateway" -> "keycloak": /.../openid-connect/token
"keycloak" ->> "auth-gateway": Токен доступа, подписанный keycloak\n{\n   "access_token": "eyJhbGciOi...",\n    ...\n}
"auth-gateway" -> "keycloak": /.../openid-connect/userinfo
"keycloak" ->> "auth-gateway": Информация о пользователе\n (username, email, roles ...)
"auth-gateway" --> "frontend": /login?code=...

"frontend" -> "auth-gateway": /oauth/token
"auth-gateway" ->> "frontend": Токен доступа, подписанный auth-gateway\n{\n   "access_token": "eyJhbGciOi...",\n    ...\n}
"frontend" -> "auth-gateway": /userinfo
"auth-gateway" ->> "frontend": Обогащенная информация о пользователе\n (keycloak userinfo + permissions, organizations)

"frontend" --> "User (browser)": Успешный вход на\n   localhost:8080

legend
<img:/auth-gateway-flow-legend.png>
endlegend

@enduml