access:
  auth-server-uri: https://keycloak8.i-novus.ru/auth/realms/${access.keycloak.realm}/protocol/openid-connect
  email-as-username: false
  keycloak:
    redirect-url: http://localhost:8080
    realm: security-admin
    logout-uri: /
  service:
    url: http://localhost:9090/api
    userinfo-url: http://localhost:9090/userinfo
  system:
    enabled: true

n2o:
  access:
    deny_urls: false
    schema:
      id: security
  application:
    id: security
  homepage:
    id: users

spring:
  security.oauth2.client:
    registration:
      admin-web:
        client-id: admin-web
        client-secret: fbcf4023-afe0-4ba1-944e-7a0f675b0b98
        provider: keycloak
        authorization-grant-type: authorization_code
        scope:
          - openid

    provider:
      keycloak:
        issuer-uri: https://keycloak8.i-novus.ru/auth/realms/${access.keycloak.realm}


server.servlet.encoding:
  force: true
  force-response: true
